let suggestions = [
    "Brawl Stars",
    "Clash Royale",
    "Among Us",
    "Fortnite",
    "Call of Duty",
    "League of Legends",
    "PUBG",
    "Apex Legends",
    "Minecraft",
    "Genshin Impact",
    "Rocket League",
    "Valorant",
    "Overwatch",
    "Candy Crush",
    "Fall Guys",
    "Animal Crossing",
    "FIFA",
    "NBA 2K",
    "Warzone",
    "Destiny 2",
    "Game lag issues",
    "How to fix server errors",
    "Tips for beginners",
    "Character leveling guide",
    "Best strategies for Brawl Stars",
    "Game not launching",
    "Account recovery",
    "How to improve FPS",
    "In-game purchases help",
    "Error codes explained",
    "How to report a bug",
    "Finding friends online",
    "Game update notes",
    "Multiplayer connection problems",
    "Customizing controls",
    "Voice chat not working",
    "Finding game modes",
    "Achievements and trophies",
    "Gameplay tutorials",
    "Best characters to use",
    "Free games like Brawl Stars",
    "Upcoming game releases",
    "Gaming news and updates",
    "Game reviews and ratings",
    "Community events",
    "E-sports tournaments",
    "Best mobile games",
    "Cross-platform play",
    "Game performance tips",
    "Mods and cheats for games",
];
